name: ðŸŽ¸ Setup new project on Stepman.AI

on:
  workflow_dispatch:

jobs:
  generate-project:
    if: >-
      ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Check out template repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACTION_KEY }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Check object (for debugging only)
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      - name: Remove all templated files in current repository
        run: |
          find . \( -name "*.jinja" -o -name "*{*" \) -exec rm -r {} +

      - name: Generate project from gh:stepmanai/project-bass
        run: >
          copier copy --vcs-ref main
          --data project_name="${{ github.event.repository.name }}"
          --data project_description="${{ github.event.repository.description }}"
          --skip README.md
          --skip debug_template.sh
          https://github.com/stepmanai/project-bass.git .

      - name: Create uv.lock file
        run: |
          make install

      - name: Run pre-commit hooks
        run: |
          uv run pre-commit run -a

      - name: Remove setup-project-on-create GitHub Action workflow
        run: |
          rm -rf ./.github/workflows/setup-project-on-create.yml

      - name: Commit to main branch with formatted changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Created ${{ github.event.repository.name }} project with setup-project-on-create workflow from project-bass."
          create_branch: false
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
